version: '0.0.4'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    healthcheck:
      disable: true
    command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOUSE_MODEL_PATH=/app/models/house_model.pt
      - TREE_MODEL_PATH=/app/models/tree_model.pt
      - PERSON_MODEL_PATH=/app/models/person_model.pt
      - DATABASE_URL=sqlite:///htp_project.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s